import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';

export default function header() {
  return (
    <>
    
      <Head>
        <title>BanHomOrganic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* icon title */}
        <link rel="icon" href="/leaf-logo.svg" />
        {/* Font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Chonburi&family=Prompt:wght@100;200;300;400;500;600;700;800;900&family=Radley&display=swap"
          rel="stylesheet"
        />

        {/* bootstrap */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
          integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
          integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
          crossorigin="anonymous"
        />
      </Head>

      {/* Navbar */}
      <nav className="navbar">
        <div className="container-fluid">
          <a className="navbar-brand logo" href="/">
            
            <Image
              src="/leaf-logo.svg"
              alt="Leaf-Logo"
              width="50"
              height="50"
            />
            <h5>Ban Hom Organic</h5>
          </a>
          <ul className="nav">
            <li className="nav-item active">
              <Link href="/product">Product</Link>
              
            </li>
            <li className="nav-item">
              <a href="#">Blog</a>
            </li>
            <li className="nav-item">
              <a href="#">About Us</a>
            </li>
            <li className="nav-item">
              <a href="#">Contact</a>
            </li>
          </ul>
          <button className="btn btn-outline-success" type="submit">
            Search
          </button>
        </div>
      </nav>
      <Head />
    </>

  )
}
